services:
  wp:
    container_name: vite-wordpress-web
    build: ./docker/wp
    depends_on:
      - mysql
    ports:
      - 80:80
    working_dir: /var/www/html/
    volumes:
      - ./dist:/var/www/html
      - ./task/setup-wp.sh:/tmp/setup-wp.sh
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: localdb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: true
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_POST_REVISIONS', false);
        define('WPLANG', 'ja');

  mysql:
    container_name: vite-wordpress-db
    platform: linux/x86_64
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: localdb
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    container_name: vite-wordpress-phpmyadmin
    platform: linux/x86_64
    image: phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 8888:80
    volumes:
      - phpmyadmin:/sessions
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

  mailcatcher:
    container_name: vite-wordpress-mail
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  phpmyadmin:
    driver: local
  mysql:
    driver: local
